name: Build

on:   
   workflow_dispatch:

    inputs:
      repo_url:
        description: 'repo_url'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'

      repo_branch:
        description: 'repo_branch'
        required: false
        default: 'master'

      edit_config:
        description: 'edit config'
        required: false
        default: 'mv config/jdcloud_re-ss-01 openwrt/.config'

      diy_sh:
        description: 'diy_sh'
        required: false
        default: 'ls'

      upload:
        description: '123 tyy2/short_time_files tyy2_crypt'
        required: false
        default: ''
        
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 更改交换空间并link构建空间
      uses: zhlhlf/maximize-build-space@master
      with:
          swap-size-mb: 8192
                      
    - name: 获取本仓库源码
      uses: actions/checkout@main

    - name: 配置环境
      run: |
        sudo apt-get update
        sudo apt-get -y install dos2unix 
       
    - name: 获取源码&替换config
      run: |
        git clone --depth 1 ${{ inputs.repo_url }} -b ${{ inputs.repo_branch }} openwrt
        rm -rf $GITHUB_WORKSPACE/openwrt/.config
        ${{ inputs.edit_config }}
 
    - name: 更新并安装feeds
      run: |
        cd openwrt 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        find ./ -maxdepth 3 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;
        
    - name: 获取软件包
      run: |
        mkdir zhlhlf
        cd openwrt   
        make defconfig
        make download -j$(nproc)
        
        #清理垃圾文件
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
         
    - name: 一系列可自定义配置
      run: |
        cd ./openwrt/package/
        . $GITHUB_WORKSPACE/scripts/packages.sh
        . $GITHUB_WORKSPACE/scripts/handles.sh

        cd ..
        . $GITHUB_WORKSPACE/scripts/settings.sh

        ${{ inputs.diy_sh }}

    - name: 编译
      run: |
        cd openwrt
        FORCE_UNSAFE_CONFIGURE=1
        make -j$(nproc) || make -j1 || make -j1 V=s
                            
    - name: zip 打包
      run: |
          mkdir out_zhlhlf 666

          echo "WRT_KVER=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^kernel - \K[\d\.]+' {} \;)" >> out_zhlhlf/package_info.txt
          echo "\n\nWRT_LIST=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^luci-(app|theme)[^ ]*' {} \; | tr '\n' ' ')" >> out_zhlhlf/package_info.txt

          rm -rf openwrt/bin/targets/*/*/packages 
          mv openwrt/bin/targets/*/* out_zhlhlf
          mv openwrt/.config out_zhlhlf/.config
          cd out_zhlhlf 

          zip -r ../666/wrt-jczhl-$(date +"%Y-%m-%d-%H").zip *
          cat package_info.txt

    - name: upload
      run: |
         curl -sL https://raw.githubusercontent.com/zhlhlf/text/refs/heads/main/upload/upload.sh | bash -s "${{ secrets.RCK }}" "${{ inputs.upload }}"

      
